# Generated by Django 5.1 on 2024-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='cover/profile/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
